### ISSUE TITLE
looking for method on how to get all the ids for the ftmo version of dx trade.

### ISSUE THREAD

**Issue by potatoesforliferi** [zLeki/DxTrade-Api-Go#1]
Hi there everyone, really great work on the initial library. 
I was inspired by your code and was writing a python version, and managed to login. 
I was trying to figure out where you found the asset number ids. 
@zLeki 
Such the ones you wrote here
`const (
	GBPUSD = 3440
	EURUSD = 3438
	USDJPY = 3427
	EURGBP = 3419
	USDCAD = 3433
	USDCHF = 3390
	AUDUSD = 3411
	NZDUSD = 3398
	EURJPY = 3392
	AUDCHF = 3395
	XAUUSD = 3406
	US30 = 3351
)`

It would be great if you could explain how you achieved that, as i plan to trade some assets that are not on this list, Being BTCUSD and US100. 

Thank you in advance :) and amazing library. Helped me a lot in making my python version i plan on releasing soon. 

![image](https://github.com/zLeki/DXTrade-Api-Go/assets/57944923/e6f067cd-add1-4693-b330-4996ccb2ba99)

**Comment by benjaminsabella** [comment]
So, the way I found those ID's was using a HTTP debugger and every time you made an order to the market it would send a http request called single and in the leg part of the json payload it would contain the id of the symbol/ticker
