### ISSUE TITLE
Will It Work with only FTMO Dxtrade Accounts or All DXTrade Accounts.

### ISSUE THREAD

**Issue by Shivamvrewa** [zLeki/DxTrade-Api-Go#7]

**Comment by benjaminsabella** [comment]
It will work with any, I believe I made an update where you type the url of where your brokerage is (such as dxtrade.ftmo.com), I believe the parameter is called vendor

**Comment by Shivamvrewa** [comment]
Hi  
I am getting error when i try to connect Dxtrade '
Post "https://dxtrade.com/api/auth/login": dial tcp 185.79.218.182:443: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
I am using server as "dxtrade.com"

Thank You
